version: '3.3'
services:
    server:
        container_name: character_generator_server
        image: tsamsonqa/character_generator_server:latest
        build: ./server
        ports: 
        -   published: 5000
            target: 5000
        environment:
            DATABASE_URI: ${DATABASE_URI}
        deploy:
            replicas: 3

    class_api:
        container_name: character_generator_class_api
        image: tsamsonqa/class_api:latest
        build: ./class_api
        deploy:
            replicas: 3
        
    race_api:
        container_name: character_generator_race_api
        image: tsamsonqa/race_api:latest
        build: ./race_api
        deploy:
            replicas: 3

    alignment_api:
        container_name: character_generator_alignment_api
        image: tsamsonqa/alignment_api:latest
        build: ./alignment_api
        deploy:
            replicas: 3