pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        
    }
    stages{
        stage("Configure Swarm"){
            steps{
                sh "cd ansible &&  /usr/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy Application"){
            steps{
                sh "bash jenkins/deploy_stack.sh"
            }
        }
    }
}