---
# tasks file for docker
- name: Install apt requiremtns
  apt:
    state: latest
    update-cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip

- name: Add docker gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
    state: present

- name: Install docker with apt
  apt:
    state: latest
    update-cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: pip docker
  pip:
    executable: pip3
    name: docker

- name: Add jenkins user 
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes