all:
  hosts:
    managers:
      hosts:
        manager:
    worker-1:
      hosts:
        worker-1:

  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'